_base_: './deepglobe.yml'

batch_size: 2

model:
  type: OCRNet
  backbone:
    type: HRNet_W18
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
  backbone_indices: [0]

loss:
  types:
    - type: DiceLoss
    - type: DiceLoss
  coef: [1, 0.4]
