_base_: './deepglobe.yml'


model:
  type: PPLiteSeg
  backbone:
    type: STDC1
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet1.tar.gz
  arm_out_chs: [32, 64, 128]
  seg_head_inter_chs: [32, 64, 64]

loss:
  types:
    - type: OhemCrossEntropyLoss
      min_kept: 260000
    - type: OhemCrossEntropyLoss
      min_kept: 260000
    - type: OhemCrossEntropyLoss
      min_kept: 260000
  coef: [1, 1, 1]
